Repository fvaleye/tracarbon, pull requests merged in 2023-06, with the labels that each got.

#190 Remove unused attributes
  tracarbon/locations/country.py
Labels: bug

#191 Bump release to 0.6.5
  poetry.lock
  pyproject.toml
Labels: release

#199 Change cloud carbon footprint repository for AWS carbon emissions
  .pre-commit-config.yaml
  poetry.lock
  pyproject.toml
  scripts/check_data.py
Labels: enhancement
